// Code generated by protoc-gen-go. DO NOT EDIT.
// source: gravatar.proto

// define the schema as being part of `main` package

package gravatar

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// defining the Gravatar Request schema
type GravatarRequest struct {
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Size                 int32    `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GravatarRequest) Reset()         { *m = GravatarRequest{} }
func (m *GravatarRequest) String() string { return proto.CompactTextString(m) }
func (*GravatarRequest) ProtoMessage()    {}
func (*GravatarRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_54cb14e52adee2f1, []int{0}
}

func (m *GravatarRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GravatarRequest.Unmarshal(m, b)
}
func (m *GravatarRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GravatarRequest.Marshal(b, m, deterministic)
}
func (m *GravatarRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GravatarRequest.Merge(m, src)
}
func (m *GravatarRequest) XXX_Size() int {
	return xxx_messageInfo_GravatarRequest.Size(m)
}
func (m *GravatarRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GravatarRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GravatarRequest proto.InternalMessageInfo

func (m *GravatarRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *GravatarRequest) GetSize() int32 {
	if m != nil {
		return m.Size
	}
	return 0
}

// defining the Gravatar Response schema
type GravatarResponse struct {
	Url                  string   `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GravatarResponse) Reset()         { *m = GravatarResponse{} }
func (m *GravatarResponse) String() string { return proto.CompactTextString(m) }
func (*GravatarResponse) ProtoMessage()    {}
func (*GravatarResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_54cb14e52adee2f1, []int{1}
}

func (m *GravatarResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GravatarResponse.Unmarshal(m, b)
}
func (m *GravatarResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GravatarResponse.Marshal(b, m, deterministic)
}
func (m *GravatarResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GravatarResponse.Merge(m, src)
}
func (m *GravatarResponse) XXX_Size() int {
	return xxx_messageInfo_GravatarResponse.Size(m)
}
func (m *GravatarResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GravatarResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GravatarResponse proto.InternalMessageInfo

func (m *GravatarResponse) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func init() {
	proto.RegisterType((*GravatarRequest)(nil), "gravatar.GravatarRequest")
	proto.RegisterType((*GravatarResponse)(nil), "gravatar.GravatarResponse")
}

func init() { proto.RegisterFile("gravatar.proto", fileDescriptor_54cb14e52adee2f1) }

var fileDescriptor_54cb14e52adee2f1 = []byte{
	// 156 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4b, 0x2f, 0x4a, 0x2c,
	0x4b, 0x2c, 0x49, 0x2c, 0xd2, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x80, 0xf1, 0x95, 0xac,
	0xb9, 0xf8, 0xdd, 0xa1, 0xec, 0xa0, 0xd4, 0xc2, 0xd2, 0xd4, 0xe2, 0x12, 0x21, 0x11, 0x2e, 0xd6,
	0xd4, 0xdc, 0xc4, 0xcc, 0x1c, 0x09, 0x46, 0x05, 0x46, 0x0d, 0xce, 0x20, 0x08, 0x47, 0x48, 0x88,
	0x8b, 0xa5, 0x38, 0xb3, 0x2a, 0x55, 0x82, 0x49, 0x81, 0x51, 0x83, 0x35, 0x08, 0xcc, 0x56, 0x52,
	0xe1, 0x12, 0x40, 0x68, 0x2e, 0x2e, 0xc8, 0xcf, 0x2b, 0x4e, 0x15, 0x12, 0xe0, 0x62, 0x2e, 0x2d,
	0x82, 0xe9, 0x05, 0x31, 0x8d, 0x42, 0x10, 0x56, 0x04, 0xa7, 0x16, 0x95, 0x65, 0x26, 0xa7, 0x0a,
	0x39, 0x72, 0x71, 0xb8, 0xa7, 0xe6, 0xa5, 0x16, 0x25, 0x96, 0xa4, 0x0a, 0x49, 0xea, 0xc1, 0x1d,
	0x87, 0xe6, 0x12, 0x29, 0x29, 0x6c, 0x52, 0x10, 0x7b, 0x92, 0xd8, 0xc0, 0x3e, 0x31, 0x06, 0x04,
	0x00, 0x00, 0xff, 0xff, 0x57, 0x8b, 0xcd, 0x43, 0xdb, 0x00, 0x00, 0x00,
}
